User.create(name: 'Bob',email: 'admin@example.com', password: '12341234', password_confirmation: '12341234')

s1 = Strategy.create(name: 'MTF Pullback with trend', description: '')

Setup.create(name: 'Break of structure', strategy: s1, description: 'Reduced risk entry')
Setup.create(name: 'Double top/bottom', strategy: s1, description: 'Risky entry')

Instrument.create(name: 'EURUSD', description: 'Euro vs US Dollar')
Instrument.create(name: 'GBPUSD', description: 'Great Britain Pound vs US Dollar')
Instrument.create(name: 'USDJPY', description: 'US Dollar vs Japanese Yen')
Instrument.create(name: 'USDCHF', description: 'US Dollar vs Swiss Franc')
Instrument.create(name: 'USDCAD', description: 'US Dollar vs Canadian')
Instrument.create(name: 'AUDUSD', description: 'Australian vs US Dollar')
Instrument.create(name: 'NZDUSD', description: 'New Zealand Dollar vs US Dollar')
Instrument.create(name: 'EURJPY', description: 'Euro vs Japanese Yen')
Instrument.create(name: 'EURCHF', description: 'Euro vs Swiss Franc')
Instrument.create(name: 'EURGBP', description: 'Euro vs Great Britain Pound')
Instrument.create(name: 'AUDCAD', description: 'Australian Dollar vs Canadian Dollar')
Instrument.create(name: 'AUDCHF', description: 'Australian Dollar vs Swiss Franc')
Instrument.create(name: 'AUDJPY', description: 'Australian Dollar vs Japanise Yen')
Instrument.create(name: 'CADCHF', description: 'Canadian Dollar vs Swiss Franc')
Instrument.create(name: 'CADJPY', description: 'Canadian Dollar vs Japanise Yen')
Instrument.create(name: 'CHFJPY', description: 'Swiss Franc vs Japanise Yen')
Instrument.create(name: 'NZDCAD', description: 'New Zealand Dollar vs Canadian Dollar')
Instrument.create(name: 'NZDCHF', description: 'New Zealand Dollar vs Swiss Franc')
Instrument.create(name: 'NZDJPY', description: 'New Zealand Dollar vs Japanise Yen')
Instrument.create(name: 'USDDKK', description: 'US Dollar vs Denmark Kroner')
Instrument.create(name: 'USDSEK', description: 'US Dollar vs Sweden Kronor')
Instrument.create(name: 'USDNOK', description: 'US Dollar vs Norway Kroner')
Instrument.create(name: 'USDZAR', description: 'US Dollar vs South Africa Rand')
Instrument.create(name: 'USDRUR', description: 'US Dollar vs Russian Ruble')
Instrument.create(name: 'EURRUR', description: 'Euro vs Russian Ruble')
Instrument.create(name: 'AUDCZK', description: 'Australian Dollar vs Czech Koruna')
Instrument.create(name: 'AUDDKK', description: 'Australian Dollar vs Denmark Kroner')
Instrument.create(name: 'AUDHKD', description: 'Australian Dollar vs Hong-Kong Dollar')
Instrument.create(name: 'AUDHUF', description: 'Australian Dollar vs Hungarian Forint')
Instrument.create(name: 'AUDMXN', description: 'Australian Dollar vs Mexican Pesos')
Instrument.create(name: 'AUDNOK', description: 'Australian Dollar vs Norway Kroner')
Instrument.create(name: 'AUDPLN', description: 'Australian Dollar vs Polish Zloty')
Instrument.create(name: 'AUDSEK', description: 'Australian Dollar vs Sweden Kronor')
Instrument.create(name: 'AUDSGD', description: 'Australian Dollar vs Singapore Dollar')
Instrument.create(name: 'AUDZAR', description: 'Australian Dollar vs South Africa Rand')
Instrument.create(name: 'CADCZK', description: 'Canadian Dollar vs Czech Koruna')
Instrument.create(name: 'CADDKK', description: 'Canadian Dollar vs Denmark Kroner')
Instrument.create(name: 'CADHKD', description: 'Canadian Dollar vs Hong-Kong Dollar')
Instrument.create(name: 'CADHUF', description: 'Canadian Dollar vs Hungarian Forint')
Instrument.create(name: 'CADMXN', description: 'Canadian Dollar vs Mexican Pesos')
Instrument.create(name: 'CADNOK', description: 'Canadian Dollar vs Norway Kroner')
Instrument.create(name: 'CADPLN', description: 'Canadian Dollar vs Polish Zloty')
Instrument.create(name: 'CADSEK', description: 'Canadian Dollar vs Sweden Kronor')
Instrument.create(name: 'CADSGD', description: 'Canadian Dollar vs Singapore Dollar')
Instrument.create(name: 'CADZAR', description: 'Canadian Dollar vs South Africa Rand')
Instrument.create(name: 'CHFCZK', description: 'Swiss Franc vs Czech Koruna')
Instrument.create(name: 'CHFDKK', description: 'Swiss Franc vs Denmark Kroner')
Instrument.create(name: 'CHFHKD', description: 'Swiss Franc vs Hong-Kong Dollar')
Instrument.create(name: 'CHFHUF', description: 'Swiss Franc vs Hungarian Forint')
Instrument.create(name: 'CHFMXN', description: 'Swiss Franc vs Mexican Pesos')
Instrument.create(name: 'CHFNOK', description: 'Swiss Franc vs Norway Kroner')
Instrument.create(name: 'CHFPLN', description: 'Swiss Franc vs Polish Zloty')
Instrument.create(name: 'CHFSEK', description: 'Swiss Franc vs Sweden Kronor')
Instrument.create(name: 'CHFSGD', description: 'Swiss Franc vs Singapore Dollar')
Instrument.create(name: 'CHFZAR', description: 'Swiss Franc vs South Africa Rand')
Instrument.create(name: 'EURCZK', description: 'Euro vs Czech Koruna')
Instrument.create(name: 'EURDKK', description: 'Euro vs Denmark Kroner')
Instrument.create(name: 'EURHKD', description: 'Euro vs Hong-Kong Dollar')
Instrument.create(name: 'EURHUF', description: 'Euro vs Hungarian Forint')
Instrument.create(name: 'EURMXN', description: 'Euro vs Mexican Pesos')
Instrument.create(name: 'EURNOK', description: 'Euro vs Norway Kroner')
Instrument.create(name: 'EURPLN', description: 'Euro vs Polish Zloty')
Instrument.create(name: 'EURSEK', description: 'Euro vs Sweden Kronor')
Instrument.create(name: 'EURSGD', description: 'Euro vs Singapore Dollar')
Instrument.create(name: 'EURZAR', description: 'Euro vs South Africa Rand')
Instrument.create(name: 'GBPCAD', description: 'Great Britain Pound vs Canadian Dollar')
Instrument.create(name: 'GBPCZK', description: 'Great Britain Pound vs Czech Koruna')
Instrument.create(name: 'GBPDKK', description: 'Great Britain Pound vs Denmark Kroner')
Instrument.create(name: 'GBPHKD', description: 'Great Britain Pound vs Hong-Kong Dollar')
Instrument.create(name: 'GBPHUF', description: 'Great Britain Pound vs Hungarian Forint')
Instrument.create(name: 'GBPMXN', description: 'Great Britain Pound vs Mexican Pesos')
Instrument.create(name: 'GBPNOK', description: 'Great Britain Pound vs Norway Kroner')
Instrument.create(name: 'GBPPLN', description: 'Great Britain Pound vs Polish Zloty')
Instrument.create(name: 'GBPSEK', description: 'Great Britain Pound vs Sweden Kronor')
Instrument.create(name: 'GBPSGD', description: 'Great Britain Pound vs Singapore Dollar')
Instrument.create(name: 'GBPZAR', description: 'Great Britain Pound vs South Africa Rand')
Instrument.create(name: 'NZDCZK', description: 'New Zeland Dollar vs Czech Koruna')
Instrument.create(name: 'NZDDKK', description: 'New Zeland Dollar vs Denmark Kroner')
Instrument.create(name: 'NZDHKD', description: 'New Zeland Dollar vs Hong Kong Dollar')
Instrument.create(name: 'NZDHUF', description: 'New Zeland Dollar vs Hungarian Forint')
Instrument.create(name: 'NZDMXN', description: 'New Zeland Dollar vs Mexican Pesos')
Instrument.create(name: 'NZDNOK', description: 'New Zeland Dollar vs Norway Kroner')
Instrument.create(name: 'NZDPLN', description: 'New Zeland Dollar vs Polish Zloty')
Instrument.create(name: 'NZDSEK', description: 'New Zeland Dollar vs Sweden Kronor')
Instrument.create(name: 'NZDSGD', description: 'New Zeland Dollar vs Singapore Dollar')
Instrument.create(name: 'NZDZAR', description: 'New Zeland Dollar vs South Africa Rand')
Instrument.create(name: 'USDCZK', description: 'US Dollar vs Czech Koruna')
Instrument.create(name: 'USDHKD', description: 'US Dollar vs Hong Kong Dollar')
Instrument.create(name: 'USDHUF', description: 'US Dollar vs Hungary Forint')
Instrument.create(name: 'USDMXN', description: 'US Dollar vs Mexican Peso')
Instrument.create(name: 'USDPLN', description: 'US Dollar vs Polish Zloty')
Instrument.create(name: 'USDSGD', description: 'US Dollar vs Singapore Dollar')
Instrument.create(name: 'CZKJPY', description: 'Czech Koruna vs Japanese Yen')
Instrument.create(name: 'DKKJPY', description: 'Denmark Kroner vs Japanese Yen')
Instrument.create(name: 'HKDJPY', description: 'Hong Kong Dollar vs Japanese Yen')
Instrument.create(name: 'HUFJPY', description: 'Hungarian Forint vs Japanese Yen')
Instrument.create(name: 'MXNJPY', description: 'Mexican Pesos vs Japanese Yen')
Instrument.create(name: 'NOKJPY', description: 'Norway Kroner vs Japanese Yen')
Instrument.create(name: 'SGDJPY', description: 'Singapore Dollar vs Japanese Yen')
Instrument.create(name: 'SEKJPY', description: 'Sweden Kronor vs Japanese Yen')
Instrument.create(name: 'ZARJPY', description: 'South Africa Rand vs Japanese Yen')
Instrument.create(name: 'USDINR', description: 'US Dollar vs India Rupee')
